# Autogenerated wrapper script for SCS_jll for aarch64-apple-darwin
export libscsdir, libscsindir

using OpenBLAS32_jll
JLLWrappers.@generate_wrapper_header("SCS")
JLLWrappers.@declare_library_product(libscsdir, "@rpath/libscsdir.dylib")
JLLWrappers.@declare_library_product(libscsindir, "@rpath/libscsindir.dylib")
function __init__()
    JLLWrappers.@generate_init_header(OpenBLAS32_jll)
    JLLWrappers.@init_library_product(
        libscsdir,
        "lib/libscsdir.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libscsindir,
        "lib/libscsindir.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
